# Generated by Django 5.2.1 on 2025-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='layer_level',
            field=models.CharField(default=1),
        ),
    ]
