# Generated by Django 5.2.1 on 2025-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item_layer_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='layer_level',
        ),
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
