# Generated by Django 5.2.1 on 2025-05-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_item_layer_level_item_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='level',
            field=models.IntegerField(editable=False),
        ),
    ]
