# Generated by Django 5.2.1 on 2025-05-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_item_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='level',
        ),
    ]
